"""Public planning API for policy-completed wrapper plans.

``WrapperPlanner`` projects a completed ``SemanticModule`` into an editable
``ModulePlan``. The records re-exported here describe that plan's binding,
shared native-entrypoint, bridge, namespace, transfer, result, lifecycle,
class, and descriptor views. They represent completed policy for later
lowering; they do not provide another policy-construction API.
"""

from .models import (
    ArgumentTransferPlan,
    ArrayHandoffPlan,
    BindingArgumentPlan,
    BindingCallbackPlan,
    BindingFunctionPlan,
    BindingLifecyclePlan,
    BindingModulePlan,
    BindingModuleVariablePlan,
    BindingResultPlan,
    BindingStatusErrorPlan,
    BridgeCallSlotPlan,
    BridgeArgumentPlan,
    BridgeCallbackPlan,
    BridgeFunctionPlan,
    BridgeLifecyclePlan,
    BridgeModulePlan,
    BridgeModuleVariablePlan,
    BridgeResultPlan,
    DatatypeFamily,
    DerivedFieldPlan,
    DerivedHandoffPlan,
    DerivedMemberPathPlan,
    DerivedModuleObjectPlan,
    DerivedTypePlan,
    FunctionPlan,
    GeneratedSupportProcedureEntrypointPlan,
    GeneratedSupportProcedureImplementationOwner,
    LifecycleActionPlan,
    ModulePlan,
    ModuleVariablePlan,
    NativeGeneratedCodeGroupKind,
    NativeGeneratedCodeGroupPlan,
    NativeEntrypointABIValueKind,
    NativeEntrypointABIValuePlan,
    NativeEntrypointArgumentPlan,
    NativeEntrypointCallbackPlan,
    NativeEntrypointFunctionPlan,
    NativeEntrypointModulePlan,
    NativeEntrypointModuleVariablePlan,
    NativeEntrypointParameterPlan,
    NativeEntrypointResultPlan,
    NativeEntrypointSignaturePlan,
    NativeArrayActualPlan,
    NativeArrayDefaultHandlePlan,
    NativeArrayHandlePlan,
    NativeDescriptorHandoffPlan,
    NamespacePlan,
    ResultPlan,
    ScalarDescriptorResultPlan,
    TransformationPlan,
    WrapperPlanDiagnostic,
)
from .planner import WrapperPlanner

__all__ = (
    "ArgumentTransferPlan",
    "ArrayHandoffPlan",
    "BindingArgumentPlan",
    "BindingCallbackPlan",
    "BindingFunctionPlan",
    "BindingLifecyclePlan",
    "BindingModulePlan",
    "BindingModuleVariablePlan",
    "BindingResultPlan",
    "BindingStatusErrorPlan",
    "BridgeArgumentPlan",
    "BridgeCallSlotPlan",
    "BridgeCallbackPlan",
    "BridgeFunctionPlan",
    "BridgeLifecyclePlan",
    "BridgeModulePlan",
    "BridgeModuleVariablePlan",
    "BridgeResultPlan",
    "DatatypeFamily",
    "DerivedFieldPlan",
    "DerivedHandoffPlan",
    "DerivedMemberPathPlan",
    "DerivedModuleObjectPlan",
    "DerivedTypePlan",
    "FunctionPlan",
    "GeneratedSupportProcedureEntrypointPlan",
    "GeneratedSupportProcedureImplementationOwner",
    "LifecycleActionPlan",
    "ModulePlan",
    "ModuleVariablePlan",
    "NamespacePlan",
    "NativeArrayActualPlan",
    "NativeArrayDefaultHandlePlan",
    "NativeArrayHandlePlan",
    "NativeDescriptorHandoffPlan",
    "NativeEntrypointABIValueKind",
    "NativeEntrypointABIValuePlan",
    "NativeEntrypointArgumentPlan",
    "NativeEntrypointCallbackPlan",
    "NativeEntrypointFunctionPlan",
    "NativeEntrypointModulePlan",
    "NativeEntrypointModuleVariablePlan",
    "NativeEntrypointParameterPlan",
    "NativeEntrypointResultPlan",
    "NativeEntrypointSignaturePlan",
    "NativeGeneratedCodeGroupKind",
    "NativeGeneratedCodeGroupPlan",
    "ResultPlan",
    "ScalarDescriptorResultPlan",
    "TransformationPlan",
    "WrapperPlanDiagnostic",
    "WrapperPlanner",
)
