"""Authoritative classification and coverage expectations for reference BLAS."""

from __future__ import annotations


ROUTINE_GROUPS: dict[str, tuple[str, ...]] = {
    "BLAS Level 1 real": (
        "sasum",
        "dasum",
        "saxpy",
        "daxpy",
        "scopy",
        "dcopy",
        "sdot",
        "ddot",
        "sdsdot",
        "dsdot",
        "snrm2",
        "dnrm2",
        "srot",
        "drot",
        "srotg",
        "drotg",
        "srotm",
        "drotm",
        "srotmg",
        "drotmg",
        "sscal",
        "dscal",
        "sswap",
        "dswap",
        "isamax",
        "idamax",
    ),
    "BLAS Level 1 complex": (
        "scasum",
        "dzasum",
        "caxpy",
        "zaxpy",
        "ccopy",
        "zcopy",
        "cdotc",
        "zdotc",
        "cdotu",
        "zdotu",
        "scnrm2",
        "dznrm2",
        "crotg",
        "zrotg",
        "cscal",
        "zscal",
        "csscal",
        "zdscal",
        "csrot",
        "zdrot",
        "cswap",
        "zswap",
        "icamax",
        "izamax",
    ),
    "BLAS Level 2 general": (
        "sgemv",
        "dgemv",
        "cgemv",
        "zgemv",
        "sger",
        "dger",
        "cgeru",
        "zgeru",
        "cgerc",
        "zgerc",
    ),
    "BLAS Level 2 symmetric": (
        "ssymv",
        "dsymv",
        "ssyr",
        "dsyr",
        "ssyr2",
        "dsyr2",
    ),
    "BLAS Level 2 Hermitian": (
        "chemv",
        "zhemv",
        "cher",
        "zher",
        "cher2",
        "zher2",
    ),
    "BLAS Level 2 triangular": (
        "strmv",
        "dtrmv",
        "ctrmv",
        "ztrmv",
        "strsv",
        "dtrsv",
        "ctrsv",
        "ztrsv",
    ),
    "BLAS Level 2 packed": (
        "sspmv",
        "dspmv",
        "sspr",
        "dspr",
        "sspr2",
        "dspr2",
        "chpmv",
        "zhpmv",
        "chpr",
        "zhpr",
        "chpr2",
        "zhpr2",
        "stpmv",
        "dtpmv",
        "ctpmv",
        "ztpmv",
        "stpsv",
        "dtpsv",
        "ctpsv",
        "ztpsv",
    ),
    "BLAS Level 2 banded": (
        "sgbmv",
        "dgbmv",
        "cgbmv",
        "zgbmv",
        "ssbmv",
        "dsbmv",
        "chbmv",
        "zhbmv",
        "stbmv",
        "dtbmv",
        "ctbmv",
        "ztbmv",
        "stbsv",
        "dtbsv",
        "ctbsv",
        "ztbsv",
    ),
    "BLAS Level 3 general": (
        "sgemm",
        "dgemm",
        "cgemm",
        "zgemm",
        "sgemmtr",
        "dgemmtr",
        "cgemmtr",
        "zgemmtr",
    ),
    "BLAS Level 3 symmetric": (
        "ssymm",
        "dsymm",
        "csymm",
        "zsymm",
        "ssyrk",
        "dsyrk",
        "csyrk",
        "zsyrk",
        "ssyr2k",
        "dsyr2k",
        "csyr2k",
        "zsyr2k",
    ),
    "BLAS Level 3 Hermitian": (
        "chemm",
        "zhemm",
        "cherk",
        "zherk",
        "cher2k",
        "zher2k",
    ),
    "BLAS Level 3 triangular": (
        "strmm",
        "dtrmm",
        "ctrmm",
        "ztrmm",
        "strsm",
        "dtrsm",
        "ctrsm",
        "ztrsm",
    ),
    "Auxiliary and error reporting": (
        "scabs1",
        "dcabs1",
        "lsame",
        "xerbla",
        "xerbla_array",
    ),
}

ALL_ROUTINES = tuple(routine for routines in ROUTINE_GROUPS.values() for routine in routines)
PRIK_TESTED_ROUTINES = frozenset(ALL_ROUTINES)

# f2py infers these scalar arguments as input-only from the unannotated reference
# sources. The native calls run, but updated scalar values are not projected back
# to Python. Their tests validate PRIK completely and compare any observable f2py
# array mutation.
F2PY_LIMITATIONS: dict[str, str] = {
    "srotg": "f2py returns None and exposes none of the four updated scalar arguments",
    "drotg": "f2py returns None and exposes none of the four updated scalar arguments",
    "crotg": "f2py returns None and exposes none of the four updated scalar arguments",
    "zrotg": "f2py returns None and exposes none of the four updated scalar arguments",
    "srotmg": "f2py exposes PARAM mutation but not the updated D1, D2, and X1 scalars",
    "drotmg": "f2py exposes PARAM mutation but not the updated D1, D2, and X1 scalars",
}

DIFFERENTIALLY_TESTED_ROUTINES = frozenset(ALL_ROUTINES) - F2PY_LIMITATIONS.keys()

UNSUPPORTED_ROUTINES: dict[str, str] = {}
PERMANENTLY_SKIPPED_ROUTINES: dict[str, str] = {}

EXPLICIT_TEST_NAMES = {routine: f"test_{routine}" for routine in ALL_ROUTINES}
EXPLICIT_TEST_NAMES["dgemv"] = "test_dgemv_no_transpose"
EXPLICIT_TEST_NAMES["dtrsv"] = "test_dtrsv_upper_nonunit"
