"""Pre-parse source preparation and compiler-derived target facts."""

from .source import (
    CommandTemplateAdapter,
    CompilerAdapter,
    GCCCompatibleCAdapter,
    GNUFortranAdapter,
    IncludedFile,
    Invocation,
    MacroDefinition,
    PreprocessResult,
    PreprocessingConfig,
    PreprocessingDiagnostic,
    PreprocessingError,
    PreprocessingPlan,
    PreprocessingRecipe,
    SourceMapping,
    build_compile_commands_invocation,
    build_direct_preprocess_invocation,
    build_preprocess_invocation,
    build_template_preprocess_invocation,
    parse_linemarker_mappings,
    preprocess_source,
    run_compiler_preprocessor,
    run_compiler_preprocessor_with_recipe,
    validate_macro_name,
)
from .fortran import expand_native_fortran_includes

__all__ = (
    "CommandTemplateAdapter",
    "CompilerAdapter",
    "GCCCompatibleCAdapter",
    "GNUFortranAdapter",
    "IncludedFile",
    "Invocation",
    "MacroDefinition",
    "PreprocessResult",
    "PreprocessingConfig",
    "PreprocessingDiagnostic",
    "PreprocessingError",
    "PreprocessingPlan",
    "PreprocessingRecipe",
    "SourceMapping",
    "build_compile_commands_invocation",
    "build_direct_preprocess_invocation",
    "build_preprocess_invocation",
    "build_template_preprocess_invocation",
    "expand_native_fortran_includes",
    "parse_linemarker_mappings",
    "preprocess_source",
    "run_compiler_preprocessor",
    "run_compiler_preprocessor_with_recipe",
    "validate_macro_name",
)
