#[=======================================================================[.rst:

UsePRIK
-------

Create a Python extension whose wrapper sources are generated by PRIK and
whose native compilation and linking are owned by CMake.

]=======================================================================]

include_guard(GLOBAL)
include(CMakeParseArguments)

if(NOT Python_EXECUTABLE OR NOT COMMAND Python_add_library)
    find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)
endif()

function(_prik_make_absolute_paths output_variable)
    set(_absolute_paths)
    foreach(_path IN LISTS ARGN)
        if(IS_ABSOLUTE "${_path}")
            list(APPEND _absolute_paths "${_path}")
        else()
            get_filename_component(_absolute_path "${_path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
            list(APPEND _absolute_paths "${_absolute_path}")
        endif()
    endforeach()
    set(${output_variable} "${_absolute_paths}" PARENT_SCOPE)
endfunction()

function(_prik_validate_source_suffixes language sources)
    foreach(_source IN LISTS ${sources})
        get_filename_component(_suffix "${_source}" LAST_EXT)
        string(TOLOWER "${_suffix}" _suffix)
        if(language STREQUAL "fortran")
            if(NOT _suffix MATCHES "^\\.(f|f03|f08|f77|f90|f95|for|ftn)$")
                message(FATAL_ERROR "PRIK Fortran input is not a supported source: ${_source}")
            endif()
        elseif(NOT _suffix STREQUAL ".c")
            message(FATAL_ERROR "PRIK C input is not a supported source: ${_source}")
        endif()
    endforeach()
endfunction()

function(_prik_append_cli_flags command option flags)
    set(_command ${${command}})
    foreach(_flag IN LISTS ${flags})
        list(APPEND _command "${option}=${_flag}")
    endforeach()
    set(${command} "${_command}" PARENT_SCOPE)
endfunction()

function(_prik_json_string_list output_variable json)
    set(_prik_json_path ${ARGN})
    string(JSON _prik_item_count ERROR_VARIABLE _prik_json_error LENGTH "${json}" ${_prik_json_path})
    if(_prik_json_error)
        message(FATAL_ERROR "PRIK did not return ${_prik_json_path}: ${_prik_json_error}")
    endif()

    set(_prik_items)
    if(_prik_item_count GREATER 0)
        math(EXPR _prik_last_item_index "${_prik_item_count} - 1")
        foreach(_prik_item_index RANGE 0 ${_prik_last_item_index})
            string(JSON _prik_item GET "${json}" ${_prik_json_path} ${_prik_item_index})
            list(APPEND _prik_items "${_prik_item}")
        endforeach()
    endif()
    set(${output_variable} "${_prik_items}" PARENT_SCOPE)
endfunction()

function(_prik_rebase_plan_path output_variable path source_root output_root)
    file(RELATIVE_PATH _prik_relative_path "${source_root}" "${path}")
    if(_prik_relative_path STREQUAL "")
        set(_prik_rebased_path "${output_root}")
    elseif(NOT _prik_relative_path MATCHES "^\\.\\.")
        set(_prik_rebased_path "${output_root}/${_prik_relative_path}")
    else()
        set(_prik_rebased_path "${path}")
    endif()
    set(${output_variable} "${_prik_rebased_path}" PARENT_SCOPE)
endfunction()

function(_prik_rebase_generated_paths output_variable paths source_root output_root)
    set(_prik_rebased_paths)
    foreach(_prik_path IN LISTS ${paths})
        file(RELATIVE_PATH _prik_relative_path "${source_root}" "${_prik_path}")
        if(_prik_relative_path MATCHES "^\\.\\.")
            message(FATAL_ERROR "PRIK generated output is outside its output directory: ${_prik_path}")
        endif()
        list(APPEND _prik_rebased_paths "${output_root}/${_prik_relative_path}")
    endforeach()
    set(${output_variable} "${_prik_rebased_paths}" PARENT_SCOPE)
endfunction()

function(_prik_apply_compilation_unit target json group index generated source_root output_root)
    if(group STREQUAL "native")
        set(_prik_unit_path native_build_plan compilation_units)
    else()
        set(_prik_unit_path generated_compilation_units)
    endif()
    string(JSON _prik_unit_source GET "${json}" ${_prik_unit_path} ${index} source)
    string(JSON _prik_unit_language GET "${json}" ${_prik_unit_path} ${index} language)
    if(generated)
        _prik_rebase_plan_path(
            _prik_unit_source "${_prik_unit_source}" "${source_root}" "${output_root}"
        )
    endif()
    _prik_json_string_list(_prik_unit_flags "${json}" ${_prik_unit_path} ${index} flags)
    _prik_json_string_list(_prik_unit_abi_flags "${json}" ${_prik_unit_path} ${index} abi_flags)
    _prik_json_string_list(_prik_unit_include_dirs "${json}" ${_prik_unit_path} ${index} include_dirs)

    set(_prik_rebased_include_dirs)
    foreach(_prik_include_dir IN LISTS _prik_unit_include_dirs)
        _prik_rebase_plan_path(
            _prik_rebased_include_dir "${_prik_include_dir}" "${source_root}" "${output_root}"
        )
        list(APPEND _prik_rebased_include_dirs "${_prik_rebased_include_dir}")
    endforeach()
    if(_prik_unit_flags)
        set_property(
            SOURCE "${_prik_unit_source}"
            APPEND PROPERTY COMPILE_OPTIONS ${_prik_unit_flags}
        )
    endif()
    if(_prik_unit_language STREQUAL "fortran")
        set(_prik_cmake_unit_language Fortran)
    else()
        set(_prik_cmake_unit_language C)
    endif()
    foreach(_prik_abi_flag IN LISTS _prik_unit_abi_flags)
        set(_prik_abi_key "${_prik_cmake_unit_language}:${_prik_abi_flag}")
        get_property(_prik_applied_abi_flags TARGET "${target}" PROPERTY _PRIK_APPLIED_ABI_FLAGS)
        if(NOT _prik_abi_key IN_LIST _prik_applied_abi_flags)
            target_compile_options(
                "${target}" PRIVATE "$<$<COMPILE_LANGUAGE:${_prik_cmake_unit_language}>:${_prik_abi_flag}>"
            )
            set_property(TARGET "${target}" APPEND PROPERTY _PRIK_APPLIED_ABI_FLAGS "${_prik_abi_key}")
        endif()
    endforeach()
    if(_prik_rebased_include_dirs)
        set_property(
            SOURCE "${_prik_unit_source}"
            APPEND PROPERTY INCLUDE_DIRECTORIES ${_prik_rebased_include_dirs}
        )
    endif()
endfunction()

function(_prik_validate_args args)
    foreach(_prik_arg IN LISTS ${args})
        if(_prik_arg MATCHES "^--(analysis-fortran-compiler|build-manifest|cmake|compiler|json|jobs|language|lto|makefile|module-name|native-c-compile-flags|native-c-sources|native-compile-flags|native-fortran-sources|native-library|native-library-dir|native-link-item|native-linker-language|native-objects|no-compile-input-sources|no-standard-logicals|out|out-dir|plan|pyi|sources|wrapper-c-flags|wrapper-compiler-debug|wrapper-fortran-flags)(=|$)")
            message(FATAL_ERROR "PRIK_ARGS cannot override prik_add_module build ownership: ${_prik_arg}")
        endif()
    endforeach()
endfunction()

function(prik_add_module name)
    if(NOT name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "PRIK module name must be a Python/CMake identifier: ${name}")
    endif()
    if(TARGET "${name}")
        message(FATAL_ERROR "PRIK module target already exists: ${name}")
    endif()

    set(_options NO_COMPILE_INPUT_SOURCES NO_STANDARD_LOGICALS)
    set(_one_value_arguments CONTRACT LINKER_LANGUAGE)
    set(_multi_value_arguments
        SOURCES
        FORTRAN_SOURCES
        C_SOURCES
        INCLUDE_DIRS
        MODULE_DIRS
        FORTRAN_FLAGS
        C_FLAGS
        WRAPPER_FORTRAN_FLAGS
        WRAPPER_C_FLAGS
        LINK_LIBRARIES
        LINK_OPTIONS
        PRIK_ARGS
    )
    cmake_parse_arguments(PRIK "${_options}" "${_one_value_arguments}" "${_multi_value_arguments}" ${ARGN})
    if(PRIK_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown prik_add_module arguments: ${PRIK_UNPARSED_ARGUMENTS}")
    endif()
    _prik_validate_args(PRIK_PRIK_ARGS)

    if(PRIK_CONTRACT AND PRIK_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) cannot combine CONTRACT and SOURCES")
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES AND NOT PRIK_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) uses NO_COMPILE_INPUT_SOURCES only with SOURCES")
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES AND NOT PRIK_FORTRAN_SOURCES AND NOT PRIK_C_SOURCES AND NOT PRIK_LINK_LIBRARIES)
        message(FATAL_ERROR "prik_add_module(${name}) requires native implementation sources or LINK_LIBRARIES")
    endif()
    if(NOT PRIK_CONTRACT AND NOT PRIK_SOURCES AND NOT PRIK_FORTRAN_SOURCES AND NOT PRIK_C_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) requires SOURCES, FORTRAN_SOURCES, C_SOURCES, or CONTRACT")
    endif()

    _prik_make_absolute_paths(_prik_contract "${PRIK_CONTRACT}")
    _prik_make_absolute_paths(_prik_sources ${PRIK_SOURCES})
    _prik_make_absolute_paths(_prik_fortran_sources ${PRIK_FORTRAN_SOURCES})
    _prik_make_absolute_paths(_prik_c_sources ${PRIK_C_SOURCES})
    _prik_make_absolute_paths(_prik_include_dirs ${PRIK_INCLUDE_DIRS})
    _prik_make_absolute_paths(_prik_module_dirs ${PRIK_MODULE_DIRS})

    if(PRIK_LINKER_LANGUAGE)
        string(TOLOWER "${PRIK_LINKER_LANGUAGE}" _prik_linker_language)
        if(NOT _prik_linker_language STREQUAL "c" AND NOT _prik_linker_language STREQUAL "fortran")
            message(FATAL_ERROR "prik_add_module(${name}) LINKER_LANGUAGE must be C or Fortran")
        endif()
    endif()

    if(_prik_contract)
        set(_prik_wrapper_sources)
        set(_prik_native_fortran_sources ${_prik_fortran_sources})
        set(_prik_native_c_sources ${_prik_c_sources})
        if(_prik_native_fortran_sources)
            set(_prik_language fortran)
        elseif(_prik_native_c_sources)
            set(_prik_language c)
        elseif(PRIK_LINK_LIBRARIES AND _prik_linker_language)
            set(_prik_language "${_prik_linker_language}")
        else()
            message(FATAL_ERROR "PRIK contract module ${name} requires native sources, or LINK_LIBRARIES with LINKER_LANGUAGE")
        endif()
    else()
        if(_prik_sources)
            set(_prik_wrapper_sources ${_prik_sources})
            set(_prik_native_fortran_sources ${_prik_fortran_sources})
            set(_prik_native_c_sources ${_prik_c_sources})
        elseif(_prik_fortran_sources AND NOT _prik_c_sources)
            set(_prik_wrapper_sources ${_prik_fortran_sources})
            set(_prik_native_fortran_sources)
            set(_prik_native_c_sources)
        elseif(_prik_c_sources AND NOT _prik_fortran_sources)
            set(_prik_wrapper_sources ${_prik_c_sources})
            set(_prik_native_fortran_sources)
            set(_prik_native_c_sources)
        else()
            message(FATAL_ERROR "PRIK module ${name} cannot mix Fortran and C wrapper sources")
        endif()

        list(GET _prik_wrapper_sources 0 _prik_first_source)
        get_filename_component(_prik_first_suffix "${_prik_first_source}" LAST_EXT)
        string(TOLOWER "${_prik_first_suffix}" _prik_first_suffix)
        if(_prik_first_suffix STREQUAL ".c")
            set(_prik_language c)
        else()
            set(_prik_language fortran)
        endif()
    endif()

    _prik_validate_source_suffixes("${_prik_language}" _prik_wrapper_sources)
    _prik_validate_source_suffixes(fortran _prik_native_fortran_sources)
    _prik_validate_source_suffixes(c _prik_native_c_sources)

    set(_prik_output_dir "${CMAKE_CURRENT_BINARY_DIR}/prik/${name}")
    file(MAKE_DIRECTORY "${_prik_output_dir}")

    if(_prik_language STREQUAL "fortran")
        set(_prik_analysis_compiler "${CMAKE_Fortran_COMPILER}")
    else()
        set(_prik_analysis_compiler "${CMAKE_C_COMPILER}")
    endif()
    if(NOT _prik_analysis_compiler)
        message(FATAL_ERROR "PRIK module ${name} requires CMake to enable ${_prik_language}")
    endif()

    set(_prik_generate_command "${Python_EXECUTABLE}" -m prik generate --sources)
    if(_prik_contract)
        list(APPEND _prik_generate_command "${_prik_contract}")
    else()
        list(APPEND _prik_generate_command ${_prik_wrapper_sources})
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES)
        list(APPEND _prik_generate_command --no-compile-input-sources)
    endif()
    if((PRIK_NO_COMPILE_INPUT_SOURCES OR _prik_contract) AND NOT _prik_native_fortran_sources AND NOT _prik_native_c_sources)
        list(APPEND _prik_generate_command --external-native-implementation)
    endif()
    list(APPEND _prik_generate_command --module-name "${name}")
    list(APPEND _prik_generate_command --language "${_prik_language}")
    # PRIK analyzes and probes with CMake's selected compiler; CMake retains
    # ownership of all actual compilation and linking.
    list(APPEND _prik_generate_command --compiler "${_prik_analysis_compiler}")
    if(CMAKE_Fortran_COMPILER)
        list(APPEND _prik_generate_command --analysis-fortran-compiler "${CMAKE_Fortran_COMPILER}")
    endif()
    _prik_append_cli_flags(_prik_generate_command --native-compile-flags PRIK_FORTRAN_FLAGS)
    _prik_append_cli_flags(_prik_generate_command --native-c-compile-flags PRIK_C_FLAGS)
    _prik_append_cli_flags(_prik_generate_command --wrapper-fortran-flags PRIK_WRAPPER_FORTRAN_FLAGS)
    _prik_append_cli_flags(_prik_generate_command --wrapper-c-flags PRIK_WRAPPER_C_FLAGS)
    if(PRIK_NO_STANDARD_LOGICALS)
        list(APPEND _prik_generate_command --no-standard-logicals)
    endif()
    if(_prik_linker_language)
        list(APPEND _prik_generate_command --native-linker-language "${_prik_linker_language}")
    endif()
    foreach(_include_dir IN LISTS _prik_include_dirs _prik_module_dirs)
        list(APPEND _prik_generate_command -I "${_include_dir}")
    endforeach()
    if(_prik_native_fortran_sources)
        list(APPEND _prik_generate_command --native-fortran-sources ${_prik_native_fortran_sources})
    endif()
    if(_prik_native_c_sources)
        list(APPEND _prik_generate_command --native-c-sources ${_prik_native_c_sources})
    endif()
    list(APPEND _prik_generate_command ${PRIK_PRIK_ARGS})
    list(APPEND _prik_generate_command --json)

    # Ask PRIK's completed plan for canonical output names without materializing
    # sources. The actual source generation remains the custom command below.
    set(_prik_plan_dir "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/prik-plan/${name}")
    file(REMOVE_RECURSE "${_prik_plan_dir}")
    set(_prik_plan_command ${_prik_generate_command} --plan --out-dir "${_prik_plan_dir}")

    execute_process(
        COMMAND ${_prik_plan_command}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE _prik_configure_result
        OUTPUT_VARIABLE _prik_plan_json
        ERROR_VARIABLE _prik_configure_error
    )
    if(NOT _prik_configure_result EQUAL 0)
        message(FATAL_ERROR "PRIK wrapper generation failed for ${name}:\n${_prik_configure_error}")
    endif()

    _prik_json_string_list(_prik_planned_sources "${_prik_plan_json}" generated_sources)
    if(NOT _prik_planned_sources)
        message(FATAL_ERROR "PRIK did not return generated wrapper sources for ${name}")
    endif()
    _prik_json_string_list(_prik_planned_outputs "${_prik_plan_json}" generated_files)
    if(NOT _prik_planned_outputs)
        message(FATAL_ERROR "PRIK did not return generated outputs for ${name}")
    endif()
    _prik_json_string_list(_prik_semantic_dependencies "${_prik_plan_json}" semantic_dependencies)
    _prik_json_string_list(_prik_extension_link_flags "${_prik_plan_json}" extension_link_flags)

    string(JSON _prik_linker_language_type TYPE "${_prik_plan_json}" linker_language)
    if(_prik_linker_language_type STREQUAL "STRING")
        string(JSON _prik_required_linker_language GET "${_prik_plan_json}" linker_language)
    elseif(NOT _prik_linker_language_type STREQUAL "NULL")
        message(FATAL_ERROR "PRIK returned an invalid linker_language for ${name}")
    endif()

    string(
        JSON _prik_generated_unit_count
        ERROR_VARIABLE _prik_generated_plan_error
        LENGTH "${_prik_plan_json}" generated_compilation_units
    )
    if(_prik_generated_plan_error)
        message(FATAL_ERROR "PRIK did not return generated compilation units: ${_prik_generated_plan_error}")
    endif()

    string(
        JSON _prik_native_unit_count
        ERROR_VARIABLE _prik_native_plan_error
        LENGTH "${_prik_plan_json}" native_build_plan compilation_units
    )
    if(_prik_native_plan_error)
        message(FATAL_ERROR "PRIK did not return native compilation units: ${_prik_native_plan_error}")
    endif()
    set(_prik_native_target_sources)
    if(_prik_native_unit_count GREATER 0)
        math(EXPR _prik_last_native_unit_index "${_prik_native_unit_count} - 1")
        foreach(_prik_native_unit_index RANGE 0 ${_prik_last_native_unit_index})
            string(
                JSON _prik_native_target_source
                GET "${_prik_plan_json}" native_build_plan compilation_units ${_prik_native_unit_index} source
            )
            list(APPEND _prik_native_target_sources "${_prik_native_target_source}")
        endforeach()
    endif()

    execute_process(
        COMMAND "${Python_EXECUTABLE}" -c "import numpy; print(numpy.get_include())"
        RESULT_VARIABLE _prik_numpy_result
        OUTPUT_VARIABLE _prik_numpy_include
        ERROR_VARIABLE _prik_numpy_error
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT _prik_numpy_result EQUAL 0)
        message(FATAL_ERROR "PRIK requires NumPy headers for ${name}:\n${_prik_numpy_error}")
    endif()
    _prik_rebase_generated_paths(
        _prik_generated_sources _prik_planned_sources "${_prik_plan_dir}" "${_prik_output_dir}"
    )
    _prik_rebase_generated_paths(
        _prik_generation_outputs _prik_planned_outputs "${_prik_plan_dir}" "${_prik_output_dir}"
    )

    # Semantic inputs can add or remove a bridge source, so make CMake
    # reconfigure before it evaluates the target source list again.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_prik_semantic_dependencies})

    set(_prik_command_signature_dir "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/prik")
    file(MAKE_DIRECTORY "${_prik_command_signature_dir}")
    set(_prik_command_signature "${_prik_command_signature_dir}/${name}-generation-command.txt")
    string(JOIN "\n" _prik_command_signature_text ${_prik_generate_command} --out-dir "${_prik_output_dir}")
    file(CONFIGURE OUTPUT "${_prik_command_signature}" CONTENT "${_prik_command_signature_text}\n" @ONLY)

    set(_prik_dependencies
        ${_prik_semantic_dependencies}
        "${_prik_command_signature}"
        "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    )
    list(FILTER _prik_dependencies EXCLUDE REGEX "^$")
    set(_prik_actual_generate_command ${_prik_generate_command} --out-dir "${_prik_output_dir}")
    file(REMOVE_RECURSE "${_prik_plan_dir}")
    add_custom_command(
        OUTPUT ${_prik_generation_outputs}
        COMMAND ${_prik_actual_generate_command}
        DEPENDS ${_prik_dependencies}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        VERBATIM
        COMMENT "Generate PRIK wrapper sources for ${name}"
    )

    Python_add_library("${name}" MODULE WITH_SOABI ${_prik_generated_sources})
    set(_prik_additional_outputs ${_prik_generation_outputs})
    list(REMOVE_ITEM _prik_additional_outputs ${_prik_generated_sources})
    if(_prik_additional_outputs)
        target_sources("${name}" PRIVATE ${_prik_additional_outputs})
    endif()
    if(_prik_native_target_sources)
        target_sources("${name}" PRIVATE ${_prik_native_target_sources})
    endif()
    if(_prik_generated_unit_count GREATER 0)
        math(EXPR _prik_last_generated_unit_index "${_prik_generated_unit_count} - 1")
        foreach(_prik_generated_unit_index RANGE 0 ${_prik_last_generated_unit_index})
            _prik_apply_compilation_unit(
                "${name}" "${_prik_plan_json}" generated ${_prik_generated_unit_index} TRUE
                "${_prik_plan_dir}" "${_prik_output_dir}"
            )
        endforeach()
    endif()
    if(_prik_native_unit_count GREATER 0)
        math(EXPR _prik_last_native_unit_index "${_prik_native_unit_count} - 1")
        foreach(_prik_native_unit_index RANGE 0 ${_prik_last_native_unit_index})
            _prik_apply_compilation_unit(
                "${name}" "${_prik_plan_json}" native ${_prik_native_unit_index} FALSE
                "${_prik_plan_dir}" "${_prik_output_dir}"
            )
        endforeach()
    endif()
    set_target_properties("${name}" PROPERTIES PREFIX "" OUTPUT_NAME "${name}")
    if(_prik_required_linker_language STREQUAL "fortran")
        set_property(TARGET "${name}" PROPERTY LINKER_LANGUAGE Fortran)
    elseif(_prik_required_linker_language STREQUAL "c")
        set_property(TARGET "${name}" PROPERTY LINKER_LANGUAGE C)
    endif()
    if(_prik_required_linker_language STREQUAL "fortran")
        set_target_properties("${name}" PROPERTIES Fortran_MODULE_DIRECTORY "${_prik_output_dir}")
    endif()

    target_include_directories(
        "${name}"
        PRIVATE
            "${_prik_output_dir}"
            "${_prik_numpy_include}"
            ${_prik_include_dirs}
            ${_prik_module_dirs}
    )
    if(PRIK_LINK_LIBRARIES)
        target_link_libraries("${name}" PRIVATE ${PRIK_LINK_LIBRARIES})
    endif()
    if(_prik_extension_link_flags OR PRIK_LINK_OPTIONS)
        target_link_options("${name}" PRIVATE ${_prik_extension_link_flags} ${PRIK_LINK_OPTIONS})
    endif()
endfunction()
