#[=======================================================================[.rst:

UsePRIK
-------

Create a Python extension whose wrapper sources are generated by PRIK and
whose native compilation and linking are owned by CMake.

]=======================================================================]

include_guard(GLOBAL)
include(CMakeParseArguments)

if(NOT Python_EXECUTABLE OR NOT COMMAND Python_add_library)
    find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)
endif()

function(_prik_make_absolute_paths output_variable)
    set(_absolute_paths)
    foreach(_path IN LISTS ARGN)
        if(IS_ABSOLUTE "${_path}")
            list(APPEND _absolute_paths "${_path}")
        else()
            get_filename_component(_absolute_path "${_path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
            list(APPEND _absolute_paths "${_absolute_path}")
        endif()
    endforeach()
    set(${output_variable} "${_absolute_paths}" PARENT_SCOPE)
endfunction()

function(_prik_validate_source_suffixes language sources)
    foreach(_source IN LISTS ${sources})
        get_filename_component(_suffix "${_source}" LAST_EXT)
        string(TOLOWER "${_suffix}" _suffix)
        if(language STREQUAL "fortran")
            if(NOT _suffix MATCHES "^\\.(f|f03|f08|f77|f90|f95|for|ftn)$")
                message(FATAL_ERROR "PRIK Fortran input is not a supported source: ${_source}")
            endif()
        elseif(NOT _suffix STREQUAL ".c")
            message(FATAL_ERROR "PRIK C input is not a supported source: ${_source}")
        endif()
    endforeach()
endfunction()

function(_prik_append_cli_flags command option flags)
    set(_command ${${command}})
    foreach(_flag IN LISTS ${flags})
        list(APPEND _command "${option}=${_flag}")
    endforeach()
    set(${command} "${_command}" PARENT_SCOPE)
endfunction()

function(_prik_json_string_list output_variable json key)
    string(JSON _prik_item_count ERROR_VARIABLE _prik_json_error LENGTH "${json}" "${key}")
    if(_prik_json_error)
        message(FATAL_ERROR "PRIK did not return ${key}: ${_prik_json_error}")
    endif()

    set(_prik_items)
    if(_prik_item_count GREATER 0)
        math(EXPR _prik_last_item_index "${_prik_item_count} - 1")
        foreach(_prik_item_index RANGE 0 ${_prik_last_item_index})
            string(JSON _prik_item GET "${json}" "${key}" ${_prik_item_index})
            list(APPEND _prik_items "${_prik_item}")
        endforeach()
    endif()
    set(${output_variable} "${_prik_items}" PARENT_SCOPE)
endfunction()

function(_prik_rebase_generated_paths output_variable paths source_root output_root)
    set(_prik_rebased_paths)
    foreach(_prik_path IN LISTS ${paths})
        file(RELATIVE_PATH _prik_relative_path "${source_root}" "${_prik_path}")
        if(_prik_relative_path MATCHES "^\\.\\.")
            message(FATAL_ERROR "PRIK generated output is outside its output directory: ${_prik_path}")
        endif()
        list(APPEND _prik_rebased_paths "${output_root}/${_prik_relative_path}")
    endforeach()
    set(${output_variable} "${_prik_rebased_paths}" PARENT_SCOPE)
endfunction()

function(_prik_validate_args args)
    foreach(_prik_arg IN LISTS ${args})
        if(_prik_arg MATCHES "^--(build-manifest|cmake|json|language|makefile|module-name|native-c-sources|native-fortran-sources|no-compile-input-sources|out|out-dir|plan|pyi|sources)(=|$)")
            message(FATAL_ERROR "PRIK_ARGS cannot override prik_add_module build ownership: ${_prik_arg}")
        endif()
    endforeach()
endfunction()

function(prik_add_module name)
    if(NOT name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "PRIK module name must be a Python/CMake identifier: ${name}")
    endif()
    if(TARGET "${name}")
        message(FATAL_ERROR "PRIK module target already exists: ${name}")
    endif()

    set(_options NO_COMPILE_INPUT_SOURCES)
    set(_one_value_arguments CONTRACT)
    set(_multi_value_arguments
        SOURCES
        FORTRAN_SOURCES
        C_SOURCES
        INCLUDE_DIRS
        MODULE_DIRS
        FORTRAN_FLAGS
        C_FLAGS
        LINK_LIBRARIES
        LINK_OPTIONS
        PRIK_ARGS
    )
    cmake_parse_arguments(PRIK "${_options}" "${_one_value_arguments}" "${_multi_value_arguments}" ${ARGN})
    if(PRIK_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown prik_add_module arguments: ${PRIK_UNPARSED_ARGUMENTS}")
    endif()
    _prik_validate_args(PRIK_PRIK_ARGS)

    if(PRIK_CONTRACT AND PRIK_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) cannot combine CONTRACT and SOURCES")
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES AND NOT PRIK_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) uses NO_COMPILE_INPUT_SOURCES only with SOURCES")
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES AND NOT PRIK_FORTRAN_SOURCES AND NOT PRIK_C_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) requires native implementation sources")
    endif()
    if(NOT PRIK_CONTRACT AND NOT PRIK_SOURCES AND NOT PRIK_FORTRAN_SOURCES AND NOT PRIK_C_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) requires SOURCES, FORTRAN_SOURCES, C_SOURCES, or CONTRACT")
    endif()

    _prik_make_absolute_paths(_prik_contract "${PRIK_CONTRACT}")
    _prik_make_absolute_paths(_prik_sources ${PRIK_SOURCES})
    _prik_make_absolute_paths(_prik_fortran_sources ${PRIK_FORTRAN_SOURCES})
    _prik_make_absolute_paths(_prik_c_sources ${PRIK_C_SOURCES})
    _prik_make_absolute_paths(_prik_include_dirs ${PRIK_INCLUDE_DIRS})
    _prik_make_absolute_paths(_prik_module_dirs ${PRIK_MODULE_DIRS})

    if(_prik_contract)
        set(_prik_wrapper_sources)
        set(_prik_native_fortran_sources ${_prik_fortran_sources})
        set(_prik_native_c_sources ${_prik_c_sources})
        if(_prik_native_fortran_sources)
            set(_prik_language fortran)
        elseif(_prik_native_c_sources)
            set(_prik_language c)
        else()
            message(FATAL_ERROR "PRIK contract module ${name} requires native FORTRAN_SOURCES or C_SOURCES")
        endif()
    else()
        if(_prik_sources)
            set(_prik_wrapper_sources ${_prik_sources})
            set(_prik_native_fortran_sources ${_prik_fortran_sources})
            set(_prik_native_c_sources ${_prik_c_sources})
        elseif(_prik_fortran_sources AND NOT _prik_c_sources)
            set(_prik_wrapper_sources ${_prik_fortran_sources})
            set(_prik_native_fortran_sources)
            set(_prik_native_c_sources)
        elseif(_prik_c_sources AND NOT _prik_fortran_sources)
            set(_prik_wrapper_sources ${_prik_c_sources})
            set(_prik_native_fortran_sources)
            set(_prik_native_c_sources)
        else()
            message(FATAL_ERROR "PRIK module ${name} cannot mix Fortran and C wrapper sources")
        endif()

        list(GET _prik_wrapper_sources 0 _prik_first_source)
        get_filename_component(_prik_first_suffix "${_prik_first_source}" LAST_EXT)
        string(TOLOWER "${_prik_first_suffix}" _prik_first_suffix)
        if(_prik_first_suffix STREQUAL ".c")
            set(_prik_language c)
        else()
            set(_prik_language fortran)
        endif()
    endif()

    _prik_validate_source_suffixes("${_prik_language}" _prik_wrapper_sources)
    _prik_validate_source_suffixes(fortran _prik_native_fortran_sources)
    _prik_validate_source_suffixes(c _prik_native_c_sources)

    set(_prik_output_dir "${CMAKE_CURRENT_BINARY_DIR}/prik/${name}")
    file(MAKE_DIRECTORY "${_prik_output_dir}")

    if(_prik_language STREQUAL "fortran")
        set(_prik_analysis_compiler "${CMAKE_Fortran_COMPILER}")
    else()
        set(_prik_analysis_compiler "${CMAKE_C_COMPILER}")
    endif()
    if(NOT _prik_analysis_compiler)
        message(FATAL_ERROR "PRIK module ${name} requires CMake to enable ${_prik_language}")
    endif()

    set(_prik_generate_command "${Python_EXECUTABLE}" -m prik generate --sources)
    if(_prik_contract)
        list(APPEND _prik_generate_command "${_prik_contract}")
    else()
        list(APPEND _prik_generate_command ${_prik_wrapper_sources})
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES)
        list(APPEND _prik_generate_command --no-compile-input-sources)
    endif()
    list(APPEND _prik_generate_command --module-name "${name}")
    list(APPEND _prik_generate_command --language "${_prik_language}")
    # Later PRIK_ARGS may override this when source analysis requires a
    # distinct compiler, but CMake's selected toolchain is the default.
    list(APPEND _prik_generate_command --compiler "${_prik_analysis_compiler}")
    _prik_append_cli_flags(_prik_generate_command --native-compile-flags PRIK_FORTRAN_FLAGS)
    _prik_append_cli_flags(_prik_generate_command --native-c-compile-flags PRIK_C_FLAGS)
    foreach(_include_dir IN LISTS _prik_include_dirs _prik_module_dirs)
        list(APPEND _prik_generate_command -I "${_include_dir}")
    endforeach()
    if(_prik_native_fortran_sources)
        list(APPEND _prik_generate_command --native-fortran-sources ${_prik_native_fortran_sources})
    endif()
    if(_prik_native_c_sources)
        list(APPEND _prik_generate_command --native-c-sources ${_prik_native_c_sources})
    endif()
    list(APPEND _prik_generate_command ${PRIK_PRIK_ARGS})
    list(APPEND _prik_generate_command --json)

    # Ask PRIK's completed plan for canonical output names without materializing
    # sources. The actual source generation remains the custom command below.
    set(_prik_plan_dir "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/prik-plan/${name}")
    file(REMOVE_RECURSE "${_prik_plan_dir}")
    set(_prik_plan_command ${_prik_generate_command} --plan --out-dir "${_prik_plan_dir}")

    execute_process(
        COMMAND ${_prik_plan_command}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE _prik_configure_result
        OUTPUT_VARIABLE _prik_plan_json
        ERROR_VARIABLE _prik_configure_error
    )
    if(NOT _prik_configure_result EQUAL 0)
        message(FATAL_ERROR "PRIK wrapper generation failed for ${name}:\n${_prik_configure_error}")
    endif()

    _prik_json_string_list(_prik_planned_sources "${_prik_plan_json}" generated_sources)
    if(NOT _prik_planned_sources)
        message(FATAL_ERROR "PRIK did not return generated wrapper sources for ${name}")
    endif()
    _prik_json_string_list(_prik_planned_outputs "${_prik_plan_json}" generated_files)
    if(NOT _prik_planned_outputs)
        message(FATAL_ERROR "PRIK did not return generated outputs for ${name}")
    endif()
    _prik_json_string_list(_prik_semantic_dependencies "${_prik_plan_json}" sources)

    string(
        JSON _prik_native_unit_count
        ERROR_VARIABLE _prik_native_plan_error
        LENGTH "${_prik_plan_json}" native_build_plan compilation_units
    )
    if(_prik_native_plan_error)
        message(FATAL_ERROR "PRIK did not return native compilation units: ${_prik_native_plan_error}")
    endif()
    set(_prik_native_target_sources)
    if(_prik_native_unit_count GREATER 0)
        math(EXPR _prik_last_native_unit_index "${_prik_native_unit_count} - 1")
        foreach(_prik_native_unit_index RANGE 0 ${_prik_last_native_unit_index})
            string(
                JSON _prik_native_target_source
                GET "${_prik_plan_json}" native_build_plan compilation_units ${_prik_native_unit_index} source
            )
            list(APPEND _prik_native_target_sources "${_prik_native_target_source}")
        endforeach()
    endif()

    execute_process(
        COMMAND "${Python_EXECUTABLE}" -c "import numpy; print(numpy.get_include())"
        RESULT_VARIABLE _prik_numpy_result
        OUTPUT_VARIABLE _prik_numpy_include
        ERROR_VARIABLE _prik_numpy_error
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT _prik_numpy_result EQUAL 0)
        message(FATAL_ERROR "PRIK requires NumPy headers for ${name}:\n${_prik_numpy_error}")
    endif()
    _prik_rebase_generated_paths(
        _prik_generated_sources _prik_planned_sources "${_prik_plan_dir}" "${_prik_output_dir}"
    )
    _prik_rebase_generated_paths(
        _prik_generation_outputs _prik_planned_outputs "${_prik_plan_dir}" "${_prik_output_dir}"
    )

    # Semantic inputs can add or remove a bridge source, so make CMake
    # reconfigure before it evaluates the target source list again.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_prik_semantic_dependencies})

    set(_prik_command_signature_dir "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/prik")
    file(MAKE_DIRECTORY "${_prik_command_signature_dir}")
    set(_prik_command_signature "${_prik_command_signature_dir}/${name}-generation-command.txt")
    string(JOIN "\n" _prik_command_signature_text ${_prik_generate_command} --out-dir "${_prik_output_dir}")
    file(CONFIGURE OUTPUT "${_prik_command_signature}" CONTENT "${_prik_command_signature_text}\n" @ONLY)

    set(_prik_dependencies
        ${_prik_semantic_dependencies}
        "${_prik_command_signature}"
        "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    )
    list(FILTER _prik_dependencies EXCLUDE REGEX "^$")
    set(_prik_actual_generate_command ${_prik_generate_command} --out-dir "${_prik_output_dir}")
    file(REMOVE_RECURSE "${_prik_plan_dir}")
    add_custom_command(
        OUTPUT ${_prik_generation_outputs}
        COMMAND ${_prik_actual_generate_command}
        DEPENDS ${_prik_dependencies}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        VERBATIM
        COMMENT "Generate PRIK wrapper sources for ${name}"
    )

    Python_add_library("${name}" MODULE WITH_SOABI ${_prik_generated_sources})
    set(_prik_additional_outputs ${_prik_generation_outputs})
    list(REMOVE_ITEM _prik_additional_outputs ${_prik_generated_sources})
    if(_prik_additional_outputs)
        target_sources("${name}" PRIVATE ${_prik_additional_outputs})
    endif()
    if(_prik_native_target_sources)
        target_sources("${name}" PRIVATE ${_prik_native_target_sources})
    endif()
    set_target_properties("${name}" PROPERTIES PREFIX "" OUTPUT_NAME "${name}")
    if(_prik_language STREQUAL "fortran" OR _prik_native_fortran_sources)
        set_target_properties("${name}" PROPERTIES Fortran_MODULE_DIRECTORY "${_prik_output_dir}")
    endif()

    target_include_directories(
        "${name}"
        PRIVATE
            "${_prik_output_dir}"
            "${_prik_numpy_include}"
            ${_prik_include_dirs}
            ${_prik_module_dirs}
    )
    foreach(_flag IN LISTS PRIK_FORTRAN_FLAGS)
        target_compile_options("${name}" PRIVATE "$<$<COMPILE_LANGUAGE:Fortran>:${_flag}>")
    endforeach()
    foreach(_flag IN LISTS PRIK_C_FLAGS)
        target_compile_options("${name}" PRIVATE "$<$<COMPILE_LANGUAGE:C>:${_flag}>")
    endforeach()
    if(PRIK_LINK_LIBRARIES)
        target_link_libraries("${name}" PRIVATE ${PRIK_LINK_LIBRARIES})
    endif()
    if(PRIK_LINK_OPTIONS)
        target_link_options("${name}" PRIVATE ${PRIK_LINK_OPTIONS})
    endif()
endfunction()
