#[=======================================================================[.rst:

UsePRIK
-------

Create a Python extension whose wrapper sources are generated by PRIK and
whose native compilation and linking are owned by CMake.

]=======================================================================]

include_guard(GLOBAL)
include(CMakeParseArguments)

if(CMAKE_VERSION VERSION_LESS 3.21)
    # PRIK tracks transitive semantic inputs with add_custom_command(DEPFILE),
    # which only every supported generator accepts from 3.21 onward.
    message(
        FATAL_ERROR
        "PRIK's CMake integration requires CMake 3.21 or newer for generated dependency files."
    )
endif()

if(NOT Python_EXECUTABLE OR NOT COMMAND Python_add_library)
    find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)
endif()

function(_prik_make_absolute_paths output_variable)
    set(_absolute_paths)
    foreach(_path IN LISTS ARGN)
        if(IS_ABSOLUTE "${_path}")
            list(APPEND _absolute_paths "${_path}")
        else()
            get_filename_component(_absolute_path "${_path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
            list(APPEND _absolute_paths "${_absolute_path}")
        endif()
    endforeach()
    set(${output_variable} "${_absolute_paths}" PARENT_SCOPE)
endfunction()

function(_prik_validate_source_suffixes language sources)
    foreach(_source IN LISTS ${sources})
        get_filename_component(_suffix "${_source}" LAST_EXT)
        string(TOLOWER "${_suffix}" _lower_suffix)
        if(language STREQUAL "fortran")
            if(NOT _lower_suffix MATCHES "^\\.(f|f03|f08|f77|f90|f95|for|ftn)$")
                message(FATAL_ERROR "PRIK Fortran input is not a supported source: ${_source}")
            endif()
        elseif(NOT _lower_suffix STREQUAL ".c")
            message(FATAL_ERROR "PRIK C input is not a supported source: ${_source}")
        elseif(NOT _suffix STREQUAL ".c")
            # PRIK plans the source as C, so CMake must compile it as C too.
            message(
                FATAL_ERROR
                "PRIK C sources used through CMake must use the .c suffix; "
                ".C is interpreted as C++ by CMake: ${_source}"
            )
        endif()
    endforeach()
endfunction()

function(_prik_append_cli_flags command option flags)
    set(_command ${${command}})
    foreach(_flag IN LISTS ${flags})
        list(APPEND _command "${option}=${_flag}")
    endforeach()
    set(${command} "${_command}" PARENT_SCOPE)
endfunction()

function(_prik_json_string_list output_variable json)
    set(_prik_json_path ${ARGN})
    string(JSON _prik_item_count ERROR_VARIABLE _prik_json_error LENGTH "${json}" ${_prik_json_path})
    if(_prik_json_error)
        message(FATAL_ERROR "PRIK did not return ${_prik_json_path}: ${_prik_json_error}")
    endif()

    set(_prik_items)
    if(_prik_item_count GREATER 0)
        math(EXPR _prik_last_item_index "${_prik_item_count} - 1")
        foreach(_prik_item_index RANGE 0 ${_prik_last_item_index})
            string(JSON _prik_item GET "${json}" ${_prik_json_path} ${_prik_item_index})
            list(APPEND _prik_items "${_prik_item}")
        endforeach()
    endif()
    set(${output_variable} "${_prik_items}" PARENT_SCOPE)
endfunction()

function(_prik_add_language_options target language flags)
    # Compile-language generator expressions keep a flag group on the sources
    # it names without ever touching another PRIK target's sources.
    foreach(_prik_flag IN LISTS flags)
        target_compile_options(
            "${target}" PRIVATE "$<$<COMPILE_LANGUAGE:${language}>:${_prik_flag}>"
        )
    endforeach()
endfunction()

function(_prik_json_abi_flags output_variable json language)
    string(JSON _prik_abi_type ERROR_VARIABLE _prik_abi_error TYPE "${json}" required_abi_flags ${language})
    if(_prik_abi_error OR NOT _prik_abi_type STREQUAL "ARRAY")
        set(${output_variable} "" PARENT_SCOPE)
        return()
    endif()
    _prik_json_string_list(_prik_abi_flags "${json}" required_abi_flags ${language})
    set(${output_variable} "${_prik_abi_flags}" PARENT_SCOPE)
endfunction()


function(_prik_validate_args args)
    foreach(_prik_arg IN LISTS ${args})
        if(_prik_arg MATCHES "^--(analysis-fortran-compiler|build-manifest|cmake|cmake-plan|compiler|declared-layout|depfile|json|jobs|language|lto|makefile|module-name|native-c-compile-flags|native-c-sources|native-compile-flags|native-fortran-sources|native-library|native-library-dir|native-link-item|native-linker-language|native-objects|no-compile-input-sources|no-standard-logicals|out|out-dir|plan|pyi|sources|wrapper-c-flags|wrapper-compiler-debug|wrapper-fortran-flags)(=|$)")
            message(FATAL_ERROR "PRIK_ARGS cannot override prik_add_module build ownership: ${_prik_arg}")
        endif()
    endforeach()
endfunction()

function(prik_add_module name)
    # 1. Parse and validate the public arguments, then settle the module's
    #    structural languages before anything is created.
    if(NOT name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "PRIK module name must be a Python/CMake identifier: ${name}")
    endif()
    if(TARGET "${name}")
        message(FATAL_ERROR "PRIK module target already exists: ${name}")
    endif()

    set(_options NO_COMPILE_INPUT_SOURCES NO_STANDARD_LOGICALS)
    set(_one_value_arguments CONTRACT NATIVE_LANGUAGE LINKER_LANGUAGE)
    set(_multi_value_arguments
        SOURCES
        FORTRAN_SOURCES
        C_SOURCES
        INCLUDE_DIRS
        MODULE_DIRS
        FORTRAN_FLAGS
        C_FLAGS
        WRAPPER_FORTRAN_FLAGS
        WRAPPER_C_FLAGS
        LINK_LIBRARIES
        LIBRARY_DIRS
        LINK_OPTIONS
        PRIK_ARGS
    )
    cmake_parse_arguments(PRIK "${_options}" "${_one_value_arguments}" "${_multi_value_arguments}" ${ARGN})
    if(PRIK_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown prik_add_module arguments: ${PRIK_UNPARSED_ARGUMENTS}")
    endif()
    _prik_validate_args(PRIK_PRIK_ARGS)

    get_property(_prik_enabled_languages GLOBAL PROPERTY ENABLED_LANGUAGES)
    list(FIND _prik_enabled_languages C _prik_c_language_index)
    list(FIND _prik_enabled_languages Fortran _prik_fortran_language_index)
    if(_prik_c_language_index EQUAL -1 OR NOT CMAKE_C_COMPILER)
        message(
            FATAL_ERROR
            "PRIK Python extensions require CMake's C language to be enabled. "
            "Use project(... LANGUAGES C Fortran) or enable_language(C)."
        )
    endif()

    if(PRIK_CONTRACT AND PRIK_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) cannot combine CONTRACT and SOURCES")
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES AND NOT PRIK_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) uses NO_COMPILE_INPUT_SOURCES only with SOURCES")
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES AND NOT PRIK_FORTRAN_SOURCES AND NOT PRIK_C_SOURCES AND NOT PRIK_LINK_LIBRARIES)
        message(FATAL_ERROR "prik_add_module(${name}) requires native implementation sources or LINK_LIBRARIES")
    endif()
    if(NOT PRIK_CONTRACT AND NOT PRIK_SOURCES AND NOT PRIK_FORTRAN_SOURCES AND NOT PRIK_C_SOURCES)
        message(FATAL_ERROR "prik_add_module(${name}) requires SOURCES, FORTRAN_SOURCES, C_SOURCES, or CONTRACT")
    endif()

    _prik_make_absolute_paths(_prik_contract "${PRIK_CONTRACT}")
    _prik_make_absolute_paths(_prik_sources ${PRIK_SOURCES})
    _prik_make_absolute_paths(_prik_fortran_sources ${PRIK_FORTRAN_SOURCES})
    _prik_make_absolute_paths(_prik_c_sources ${PRIK_C_SOURCES})
    _prik_make_absolute_paths(_prik_include_dirs ${PRIK_INCLUDE_DIRS})
    _prik_make_absolute_paths(_prik_module_dirs ${PRIK_MODULE_DIRS})
    _prik_make_absolute_paths(_prik_library_dirs ${PRIK_LIBRARY_DIRS})

    if(PRIK_LINKER_LANGUAGE)
        string(TOLOWER "${PRIK_LINKER_LANGUAGE}" _prik_linker_language)
        if(NOT _prik_linker_language STREQUAL "c" AND NOT _prik_linker_language STREQUAL "fortran")
            message(FATAL_ERROR "prik_add_module(${name}) LINKER_LANGUAGE must be C or Fortran")
        endif()
    endif()
    if(PRIK_NATIVE_LANGUAGE)
        string(TOLOWER "${PRIK_NATIVE_LANGUAGE}" _prik_native_language)
        if(NOT _prik_native_language STREQUAL "c" AND NOT _prik_native_language STREQUAL "fortran")
            message(FATAL_ERROR "prik_add_module(${name}) NATIVE_LANGUAGE must be C or Fortran")
        endif()
        if(NOT _prik_contract)
            message(FATAL_ERROR "prik_add_module(${name}) NATIVE_LANGUAGE is only valid with CONTRACT")
        endif()
    endif()

    if(_prik_contract)
        set(_prik_wrapper_sources)
        set(_prik_native_fortran_sources ${_prik_fortran_sources})
        set(_prik_native_c_sources ${_prik_c_sources})
        if(_prik_native_language)
            set(_prik_language "${_prik_native_language}")
        elseif(_prik_native_fortran_sources AND _prik_native_c_sources)
            message(
                FATAL_ERROR
                "prik_add_module(${name}) CONTRACT with mixed Fortran and C implementation "
                "sources requires NATIVE_LANGUAGE"
            )
        elseif(_prik_native_fortran_sources)
            set(_prik_language fortran)
        elseif(_prik_native_c_sources)
            set(_prik_language c)
        else()
            message(
                FATAL_ERROR
                "prik_add_module(${name}) source-free CONTRACT requires NATIVE_LANGUAGE "
                "plus LINK_LIBRARIES"
            )
        endif()
        if(NOT _prik_native_fortran_sources AND NOT _prik_native_c_sources AND NOT PRIK_LINK_LIBRARIES)
            message(
                FATAL_ERROR
                "prik_add_module(${name}) source-free CONTRACT requires LINK_LIBRARIES "
                "or native implementation sources"
            )
        endif()
    else()
        if(_prik_sources)
            set(_prik_wrapper_sources ${_prik_sources})
            set(_prik_native_fortran_sources ${_prik_fortran_sources})
            set(_prik_native_c_sources ${_prik_c_sources})
        elseif(_prik_fortran_sources AND NOT _prik_c_sources)
            set(_prik_wrapper_sources ${_prik_fortran_sources})
            set(_prik_native_fortran_sources)
            set(_prik_native_c_sources)
        elseif(_prik_c_sources AND NOT _prik_fortran_sources)
            set(_prik_wrapper_sources ${_prik_c_sources})
            set(_prik_native_fortran_sources)
            set(_prik_native_c_sources)
        else()
            message(FATAL_ERROR "PRIK module ${name} cannot mix Fortran and C wrapper sources")
        endif()

        list(GET _prik_wrapper_sources 0 _prik_first_source)
        get_filename_component(_prik_first_suffix "${_prik_first_source}" LAST_EXT)
        string(TOLOWER "${_prik_first_suffix}" _prik_first_suffix)
        if(_prik_first_suffix STREQUAL ".c")
            set(_prik_language c)
        else()
            set(_prik_language fortran)
        endif()
    endif()

    _prik_validate_source_suffixes("${_prik_language}" _prik_wrapper_sources)
    _prik_validate_source_suffixes(fortran _prik_native_fortran_sources)
    _prik_validate_source_suffixes(c _prik_native_c_sources)

    if(_prik_linker_language STREQUAL "fortran")
        if(_prik_fortran_language_index EQUAL -1 OR NOT CMAKE_Fortran_COMPILER)
            message(
                FATAL_ERROR
                "PRIK module ${name} requires CMake's Fortran language to be enabled for LINKER_LANGUAGE Fortran. "
                "Use project(... LANGUAGES C Fortran) or enable_language(Fortran)."
            )
        endif()
    endif()
    if(_prik_native_fortran_sources)
        if(_prik_fortran_language_index EQUAL -1 OR NOT CMAKE_Fortran_COMPILER)
            message(
                FATAL_ERROR
                "PRIK module ${name} requires CMake's Fortran language to be enabled for its native Fortran sources. "
                "Use project(... LANGUAGES C Fortran) or enable_language(Fortran)."
            )
        endif()
    endif()

    set(_prik_output_dir "${CMAKE_CURRENT_BINARY_DIR}/prik/${name}")
    file(MAKE_DIRECTORY "${_prik_output_dir}")

    if(_prik_language STREQUAL "fortran")
        if(_prik_fortran_language_index EQUAL -1 OR NOT CMAKE_Fortran_COMPILER)
            message(FATAL_ERROR "PRIK module ${name} requires CMake to enable Fortran")
        endif()
        set(_prik_analysis_compiler "${CMAKE_Fortran_COMPILER}")
    else()
        set(_prik_analysis_compiler "${CMAKE_C_COMPILER}")
    endif()

    set(_prik_generate_command "${Python_EXECUTABLE}" -m prik generate --sources)
    if(_prik_contract)
        list(APPEND _prik_generate_command "${_prik_contract}")
    else()
        list(APPEND _prik_generate_command ${_prik_wrapper_sources})
    endif()
    if(PRIK_NO_COMPILE_INPUT_SOURCES)
        list(APPEND _prik_generate_command --no-compile-input-sources)
    endif()
    if((PRIK_NO_COMPILE_INPUT_SOURCES OR _prik_contract) AND NOT _prik_native_fortran_sources AND NOT _prik_native_c_sources)
        list(APPEND _prik_generate_command --external-native-implementation)
    endif()
    list(APPEND _prik_generate_command --module-name "${name}")
    list(APPEND _prik_generate_command --language "${_prik_language}")
    # PRIK analyzes and probes with CMake's selected compiler; CMake retains
    # ownership of all actual compilation and linking.
    list(APPEND _prik_generate_command --compiler "${_prik_analysis_compiler}")
    if(CMAKE_Fortran_COMPILER)
        list(APPEND _prik_generate_command --analysis-fortran-compiler "${CMAKE_Fortran_COMPILER}")
    endif()
    _prik_append_cli_flags(_prik_generate_command --native-compile-flags PRIK_FORTRAN_FLAGS)
    _prik_append_cli_flags(_prik_generate_command --native-c-compile-flags PRIK_C_FLAGS)
    _prik_append_cli_flags(_prik_generate_command --wrapper-fortran-flags PRIK_WRAPPER_FORTRAN_FLAGS)
    _prik_append_cli_flags(_prik_generate_command --wrapper-c-flags PRIK_WRAPPER_C_FLAGS)
    if(PRIK_NO_STANDARD_LOGICALS)
        list(APPEND _prik_generate_command --no-standard-logicals)
    endif()
    if(_prik_linker_language)
        list(APPEND _prik_generate_command --native-linker-language "${_prik_linker_language}")
    endif()
    foreach(_include_dir IN LISTS _prik_include_dirs _prik_module_dirs)
        list(APPEND _prik_generate_command -I "${_include_dir}")
    endforeach()
    if(_prik_native_fortran_sources)
        list(APPEND _prik_generate_command --native-fortran-sources ${_prik_native_fortran_sources})
    endif()
    if(_prik_native_c_sources)
        list(APPEND _prik_generate_command --native-c-sources ${_prik_native_c_sources})
    endif()
    list(APPEND _prik_generate_command ${PRIK_PRIK_ARGS})
    list(APPEND _prik_generate_command --json)

    # 2. Ask PRIK for the deterministic generated-file graph. This is a
    #    structural query: it derives filenames, the link driver, and mandatory
    #    ABI flags from the module's declared shape, and never parses a source,
    #    completes policy, or generates code. The real pipeline runs once, in
    #    the build-time custom command below.
    list(APPEND _prik_generate_command --declared-layout)
    set(_prik_plan_command ${_prik_generate_command} --cmake-plan --out-dir "${_prik_output_dir}")
    execute_process(
        COMMAND ${_prik_plan_command}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE _prik_configure_result
        OUTPUT_VARIABLE _prik_plan_json
        ERROR_VARIABLE _prik_configure_error
    )
    if(NOT _prik_configure_result EQUAL 0)
        message(FATAL_ERROR "PRIK structural planning failed for ${name}:\n${_prik_configure_error}")
    endif()

    _prik_json_string_list(_prik_generated_sources "${_prik_plan_json}" generated_sources)
    if(NOT _prik_generated_sources)
        message(FATAL_ERROR "PRIK did not return generated wrapper sources for ${name}")
    endif()
    _prik_json_string_list(_prik_generation_outputs "${_prik_plan_json}" generated_files)
    if(NOT _prik_generation_outputs)
        message(FATAL_ERROR "PRIK did not return generated outputs for ${name}")
    endif()
    string(JSON _prik_required_linker_language GET "${_prik_plan_json}" linker_language)
    string(JSON _prik_depfile GET "${_prik_plan_json}" depfile)
    _prik_json_abi_flags(_prik_fortran_abi_flags "${_prik_plan_json}" fortran)
    list(APPEND _prik_generate_command --depfile "${_prik_depfile}")

    # 3. Compile the caller's native implementation in its own object target so
    #    its flags and usage requirements stay separate from generated code.
    set(_prik_native_target_sources ${_prik_native_fortran_sources} ${_prik_native_c_sources})
    if(NOT _prik_contract AND NOT PRIK_NO_COMPILE_INPUT_SOURCES)
        list(APPEND _prik_native_target_sources ${_prik_wrapper_sources})
    endif()

    set(_prik_native_target)
    if(_prik_native_target_sources)
        set(_prik_native_target "prik_${name}_native_objects")
        if(TARGET "${_prik_native_target}")
            message(FATAL_ERROR "PRIK internal target already exists: ${_prik_native_target}")
        endif()
        add_library("${_prik_native_target}" OBJECT ${_prik_native_target_sources})
        set_target_properties("${_prik_native_target}" PROPERTIES POSITION_INDEPENDENT_CODE ON)
        if(PRIK_LINK_LIBRARIES)
            # Forward the caller's own link syntax so the native sources see the
            # usage requirements CMake would give them: debug/optimized keywords
            # and generator expressions still select per configuration, which a
            # target-only filter would flatten or drop.
            target_link_libraries("${_prik_native_target}" PRIVATE ${PRIK_LINK_LIBRARIES})
        endif()
        target_include_directories(
            "${_prik_native_target}"
            PRIVATE "${_prik_output_dir}" ${_prik_include_dirs} ${_prik_module_dirs}
        )
        _prik_add_language_options("${_prik_native_target}" C "${PRIK_C_FLAGS}")
        _prik_add_language_options("${_prik_native_target}" Fortran "${PRIK_FORTRAN_FLAGS}")
        _prik_add_language_options("${_prik_native_target}" Fortran "${_prik_fortran_abi_flags}")
        if(_prik_required_linker_language STREQUAL "fortran")
            set_target_properties(
                "${_prik_native_target}" PROPERTIES Fortran_MODULE_DIRECTORY "${_prik_output_dir}"
            )
        endif()
    endif()

    execute_process(
        COMMAND "${Python_EXECUTABLE}" -c "import numpy; print(numpy.get_include())"
        RESULT_VARIABLE _prik_numpy_result
        OUTPUT_VARIABLE _prik_numpy_include
        ERROR_VARIABLE _prik_numpy_error
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT _prik_numpy_result EQUAL 0)
        message(FATAL_ERROR "PRIK requires NumPy headers for ${name}:\n${_prik_numpy_error}")
    endif()

    # 4. Declare the one generation step. Its outputs are fixed, so a semantic
    #    edit changes file contents rather than the build graph and never needs
    #    a reconfigure. Transitive semantic inputs arrive through the depfile
    #    PRIK writes during that same run.
    set(_prik_command_signature_dir "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/prik")
    file(MAKE_DIRECTORY "${_prik_command_signature_dir}")
    set(_prik_command_signature "${_prik_command_signature_dir}/${name}-generation-command.txt")
    string(JOIN "\n" _prik_command_signature_text ${_prik_generate_command} --out-dir "${_prik_output_dir}")
    file(CONFIGURE OUTPUT "${_prik_command_signature}" CONTENT "${_prik_command_signature_text}\n" @ONLY)

    if(_prik_contract)
        set(_prik_declared_inputs "${_prik_contract}")
    else()
        set(_prik_declared_inputs ${_prik_wrapper_sources})
    endif()
    set(_prik_dependencies
        ${_prik_declared_inputs}
        "${_prik_command_signature}"
        "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    )
    list(FILTER _prik_dependencies EXCLUDE REGEX "^$")
    set(_prik_actual_generate_command ${_prik_generate_command} --out-dir "${_prik_output_dir}")
    add_custom_command(
        OUTPUT ${_prik_generation_outputs}
        COMMAND ${_prik_actual_generate_command}
        DEPENDS ${_prik_dependencies}
        DEPFILE "${_prik_depfile}"
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        VERBATIM
        COMMENT "Generate PRIK wrapper sources for ${name}"
    )

    # 5. Create the Python extension target over the fixed generated sources.
    Python_add_library("${name}" MODULE WITH_SOABI ${_prik_generated_sources})
    set(_prik_additional_outputs ${_prik_generation_outputs})
    list(REMOVE_ITEM _prik_additional_outputs ${_prik_generated_sources})
    if(_prik_additional_outputs)
        target_sources("${name}" PRIVATE ${_prik_additional_outputs})
    endif()
    if(_prik_native_target)
        target_sources("${name}" PRIVATE "$<TARGET_OBJECTS:${_prik_native_target}>")
        add_dependencies("${name}" "${_prik_native_target}")
    endif()

    # 6. Generated sources carry only the generated-code flag groups, expressed
    #    per compile language so they never leak onto native sources.
    _prik_add_language_options("${name}" C "${PRIK_WRAPPER_C_FLAGS}")
    _prik_add_language_options("${name}" Fortran "${PRIK_WRAPPER_FORTRAN_FLAGS}")
    _prik_add_language_options("${name}" Fortran "${_prik_fortran_abi_flags}")

    # 7. Link requirements: libraries, driver language, search and runtime paths.
    set_target_properties("${name}" PROPERTIES PREFIX "" OUTPUT_NAME "${name}")
    if(_prik_required_linker_language STREQUAL "fortran")
        set_property(TARGET "${name}" PROPERTY LINKER_LANGUAGE Fortran)
    elseif(_prik_required_linker_language STREQUAL "c")
        set_property(TARGET "${name}" PROPERTY LINKER_LANGUAGE C)
    endif()
    if(_prik_required_linker_language STREQUAL "fortran")
        set_target_properties("${name}" PROPERTIES Fortran_MODULE_DIRECTORY "${_prik_output_dir}")
    endif()

    target_include_directories(
        "${name}"
        PRIVATE
            "${_prik_output_dir}"
            "${_prik_numpy_include}"
            ${_prik_include_dirs}
            ${_prik_module_dirs}
    )
    if(PRIK_LINK_LIBRARIES)
        target_link_libraries("${name}" PRIVATE ${PRIK_LINK_LIBRARIES})
    endif()
    if(_prik_library_dirs)
        # A library directory is a link-time search path and, for a shared
        # native library, the runtime search path the extension needs on
        # import. INSTALL_RPATH stays under project control.
        target_link_directories("${name}" PRIVATE ${_prik_library_dirs})
        set_property(TARGET "${name}" APPEND PROPERTY BUILD_RPATH ${_prik_library_dirs})
    endif()
    if(PRIK_WRAPPER_C_FLAGS OR PRIK_LINK_OPTIONS)
        # WRAPPER_C_FLAGS reaches the extension link as well as generated C
        # compilation, matching PRIK's own build behavior.
        target_link_options("${name}" PRIVATE ${PRIK_WRAPPER_C_FLAGS} ${PRIK_LINK_OPTIONS})
    endif()
endfunction()
